name: Deploy to ftp Fornex

on:
  push:
    branches: [main]

jobs:
  deploy_to_fornex_ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to ftp 1
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FORNEX_FTP_SERVER }}
          user: ${{ secrets.FORNEX_FTP_USER }}
          password: ${{ secrets.FORNEX_FTP_PSW }}
          remote_dir: ${{ secrets.FORNEX_FTP_DIR }}
          delete: "true" # delete all files in remote directory before upload
