name: Deploy to ftp Fornex

on:
  push:
    branches: [main]

jobs:
  deploy_to_fornex_ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to ftp 1
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ftp.f59436.hostus01.fornex.host
          user: ftp_fornex@falkov.site
          password: 12Gamer1955_ftp
